### ISSUE TITLE
Nieuwe kanalen Stubru

### ISSUE THREAD

**Issue by tomcobbaert** [add-ons/plugin.audio.vrt.radio#14]
Even een 'heads-up' dat de VRT recent drie nieuwe streams heeft toegevoegd:
– Radio 2 Bene Bene
– StuBru Bruut
– StuBru Hooray

Alle links op: https://www.vrt.be/nl/aanbod/kijk-en-luister/radio-luisteren/streamingslinks-radio/

**Comment by dagwieers** [comment]
We accepteren ook pull requests ;-)

**Comment by dagwieers** [comment]
De MP3 links op https://services.vrt.be/htmlview/?href=%2Fchannel%2Fs%2F120&rel=http%3A%2F%2Fservices.vrt.be%2Fchannel%2Frel%2Fchannel blijken incorrect. Dit is gerapporteerd naar VRT.

**Comment by dagwieers** [comment]
Ze hebben het gefixed, jeuj \o/
